### ISSUE TITLE
Failed to load signer "signer #1"

### ISSUE THREAD

**Issue by StarHeartHunt** [r0adkll/sign-android-release#34]
StackTrace:
```
Verification succesful
/bin/cp app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/app-release-unsigned-aligned.apk
/usr/local/lib/android/sdk/build-tools/29.0.3/apksigner sign --ks app/build/outputs/apk/release/signingKey.jks --ks-key-alias *** --ks-pass pass: --out app/build/outputs/apk/release/app-release-unsigned-signed.apk app/build/outputs/apk/release/app-release-unsigned-aligned.apk
Failed to load signer "signer #1"
java.io.EOFException
	at java.io.DataInputStream.readInt(DataInputStream.java:392)
	at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:661)
	at sun.security.provider.JavaKeyStore$JKS.engineLoad(JavaKeyStore.java:57)
	at sun.security.provider.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:224)
	at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(JavaKeyStore.java:71)
	at java.security.KeyStore.load(KeyStore.java:1445)
	at com.android.apksigner.SignerParams.loadKeyStoreFromFile(SignerParams.java:353)
	at com.android.apksigner.SignerParams.loadPrivateKeyAndCertsFromKeyStore(SignerParams.java:239)
	at com.android.apksigner.SignerParams.loadPrivateKeyAndCerts(SignerParams.java:181)
	at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:277)
	at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:83)
Error: The process '/usr/local/lib/android/sdk/build-tools/29.0.3/apksigner' failed with exit code 2
```

**Comment by me-at-syeds-me** [comment]
I am having similar issue. No luck so far!

**Comment by soethan98** [comment]
I'm also facing this issue.

**Comment by EzequielMessore** [comment]
+1

**Comment by ankitmhatre** [comment]
@me-at-syeds-me @soethan98 Any luck ?

**Comment by thaiphandinh** [comment]
any updates on this?

**Comment by riv0manana** [comment]
Hello, I've tested this action to sign my apk. This issue is caused when wrong "signingKeyBase64" is provided.
Solution: 
run in your terminal: `openssl base64 -in your_keystore.keystore -out key.txt` and then copy the output content to your signingKeyBase64 secret.
Hope it can help you

**Comment by taori** [comment]
hm. ordinary base64 turns my keystore into 3kb file, openssl base64 turns it into 4kb. perhaps that is why some people have this error and others do not? (i have it at the moment. verifying whether it works with openssl base64)

**Comment by atanana** [comment]
I had the same error message when I misspelled "SIGNING_KEY" in my secrets 🤦‍♂

**Comment by Marwa-Eltayeb** [comment]
I have the same error. What is the solution?

**Comment by nathantaal** [comment]
For me it was me creating the wrong gitlab variables

**Comment by faizandarwesh** [comment]
Any update on this issue?

**Comment by vitalyk-multinarity** [comment]
> Hello, I've tested this action to sign my apk. This issue is caused when wrong "signingKeyBase64" is provided. Solution: run in your terminal: `openssl base64 -in your_keystore.keystore -out key.txt` and then copy the output content to your signingKeyBase64 secret. Hope it can help you

@[riv0manana](https://github.com/riv0manana) did you use key.txt as is or deleted newlines from it?

**Comment by Devanathan2015** [comment]
> Using the below command worked for me, it printed the key in console and i copied that. **openssl base64 -in your_keystore.keystore**

I tried the same. But still the issue persist for me. I encode the key-store file in mac, but i am using windows-2019 as runner.

  ```
Failed to load signer "signer #1"
  java.io.IOException: Invalid keystore format
  at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:666)
  at sun.security.provider.JavaKeyStore$JKS.engineLoad(JavaKeyStore.java:57)
  at sun.security.provider.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:224)
  at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(JavaKeyStore.java:71)
  at java.security.KeyStore.load(KeyStore.java:1445)
  at com.android.apksigner.SignerParams.loadKeyStoreFromFile(SignerParams.java:353)
  at com.android.apksigner.SignerParams.loadPrivateKeyAndCertsFromKeyStore(SignerParams.java:239)
  at com.android.apksigner.SignerParams.loadPrivateKeyAndCerts(SignerParams.java:181)
  at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:277)
  at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:83)
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2293,2): error MSB6006: "java.exe" exited with code 2. 
```

**Comment by taori** [comment]
CR/LF issue?

**Comment by ItSNeverLate** [comment]
Your password, alias, or keyword is incorrect!
Just double-check!

**Comment by nizarfadlan** [comment]
> Your password, alias, or keyword is incorrect! Just double-check!

I have tried to build through Android Studio successfully with the same key, password and alias on the Github secret but when in github actions errors like this

```
Failed to load signer "signer #1"
java.io.IOException: Tag number over 30 is not supported
	at java.base/sun.security.util.DerValue.<init>(DerValue.java:442)
	at java.base/sun.security.util.DerValue.<init>(DerValue.java:487)
	at java.base/sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:2012)
	at java.base/sun.security.util.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:221)
	at java.base/java.security.KeyStore.load(KeyStore.java:1473)
	at com.android.apksigner.SignerParams.loadKeyStoreFromFile(SignerParams.java:383)
	at com.android.apksigner.SignerParams.loadPrivateKeyAndCertsFromKeyStore(SignerParams.java:269)
	at com.android.apksigner.SignerParams.loadPrivateKeyAndCerts(SignerParams.java:202)
	at com.android.apksigner.ApkSignerTool.getSignerConfig(ApkSignerTool.java:438)
	at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:353)
	at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:92)
Error: The process '/usr/local/lib/android/sdk/build-tools/34.0.0/apksigner' failed with exit code 2
```

**Comment by yasmineDah** [comment]
> > Hello, I've tested this action to sign my apk. This issue is caused when wrong "signingKeyBase64" is provided. Solution: run in your terminal: `openssl base64 -in your_keystore.keystore -out key.txt` and then copy the output content to your signingKeyBase64 secret. Hope it can help you
> 
> @[riv0manana](https://github.com/riv0manana) did you use key.txt as is or deleted newlines from it?

I am not sure but I think delelting the newlines worked for me
