### ISSUE TITLE
Failed to load signer "signer #1" java.io.IOException: Tag number over 30 is not supported

### ISSUE THREAD

**Issue by LaxmikantMahamuni** [r0adkll/sign-android-release#91]
StackTrace:

```
Failed to load signer "signer #1"
java.io.IOException: Tag number over 30 is not supported
	at java.base/sun.security.util.DerValue.<init>(DerValue.java:442)
	at java.base/sun.security.util.DerValue.<init>(DerValue.java:487)
	at java.base/sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:2012)
	at java.base/sun.security.util.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:221)
	at java.base/java.security.KeyStore.load(KeyStore.java:1473)
	at com.android.apksigner.SignerParams.loadKeyStoreFromFile(SignerParams.java:383)
	at com.android.apksigner.SignerParams.loadPrivateKeyAndCertsFromKeyStore(SignerParams.java:269)
	at com.android.apksigner.SignerParams.loadPrivateKeyAndCerts(SignerParams.java:202)
	at com.android.apksigner.ApkSignerTool.getSignerConfig(ApkSignerTool.java:438)
	at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:353)
	at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:92)
Error: The process '/usr/local/lib/android/sdk/build-tools/34.0.0/apksigner' failed with exit code 2
```

I have checked other related issues which causes "Failed to load signer "signer #1 Failed to load signer "signer #65 Failed to load signer "signer #33. But it's hard to catch exact solution for my issue. 
Looks like, It's caused due to unable to load keystore for signing from Github.secrets may be SingingKey/keyAlias/keyPass/KeystorePass.
If anyone have pointers/solution to this please help.

![image](https://github.com/r0adkll/sign-android-release/assets/26277288/dbdfb884-b6c6-4bce-ae23-125eef027a94)

Thanks!

**Comment by LaxmikantMahamuni** [comment]
Linking, a stackoverflow questions, as it is related to this one. [Tag number over 30 is not supported](https://stackoverflow.com/questions/76574977/tag-number-over-30-is-not-supported)

**Comment by basma-eldesouki** [comment]
Got any luck?

**Comment by LaxmikantMahamuni** [comment]
> Got any luck?

I am working on different thing right now, will come on this soon.

**Comment by basma-eldesouki** [comment]
If you're facing this issue, it seems that the names of the variables in the environment variables don't match those in GitHub secrets. This includes variables like APP_KEY_STORE, APP_ALIAS, APP_KEY_STORE_PASSWORD, and APP_KEY_PASSWORD. Ensure they are consistent.

**Comment by LaxmikantMahamuni** [comment]
Really, it was not matching the env variable with Github Secret's Keys. I changed them accordingly it worked like a charm. 
Thanks!

The error message is something different which actually diverts to some other points.

**Comment by MWiyPower** [comment]
guys this is happend to me
if anyone knows how to fix it, help me
thanks

**Comment by Jobians** [comment]
Access it via `secrets.NAME`

Eg:
```
echo "${{ secrets.KEYSTORE_B64 }}" | base64 --decode > debug.keystore
          ls -l debug.keystore
```
